
-- Create product_kit_images table
CREATE TABLE public.product_kit_images (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kit_id integer NOT NULL,
  url text NOT NULL,
  storage_path text NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.product_kit_images ENABLE ROW LEVEL SECURITY;

-- RLS policies
CREATE POLICY "Users can view own kit images"
ON public.product_kit_images
FOR SELECT
TO authenticated
USING (EXISTS (
  SELECT 1 FROM public.product_kits pk
  WHERE pk.id = product_kit_images.kit_id AND pk.user_id = auth.uid()
));

CREATE POLICY "Users can insert own kit images"
ON public.product_kit_images
FOR INSERT
TO authenticated
WITH CHECK (EXISTS (
  SELECT 1 FROM public.product_kits pk
  WHERE pk.id = product_kit_images.kit_id AND pk.user_id = auth.uid()
));

CREATE POLICY "Users can delete own kit images"
ON public.product_kit_images
FOR DELETE
TO authenticated
USING (EXISTS (
  SELECT 1 FROM public.product_kits pk
  WHERE pk.id = product_kit_images.kit_id AND pk.user_id = auth.uid()
));

-- Add category column to product_kits
ALTER TABLE public.product_kits ADD COLUMN category character varying DEFAULT NULL;
